# Generated by Django 3.2 on 2022-11-07 12:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='tag',
            new_name='tags',
        ),
        migrations.RenameField(
            model_name='tagrecipe',
            old_name='tag',
            new_name='tags',
        ),
    ]
