# Generated by Django 3.2 on 2022-11-10 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_auto_20221107_1225'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ingredient',
            options={'verbose_name_plural': 'Ингредиенты'},
        ),
        migrations.AlterModelOptions(
            name='tag',
            options={'ordering': ('id',), 'verbose_name_plural': 'Теги'},
        ),
        migrations.RemoveConstraint(
            model_name='ingredientrecipe',
            name='unique_ingredient_recipe_object',
        ),
        migrations.AddConstraint(
            model_name='ingredientrecipe',
            constraint=models.UniqueConstraint(fields=('recipe', 'ingredient', 'amount'), name='unique_ingredient_recipe_object'),
        ),
    ]
