# Generated by Django 3.2 on 2022-10-26 13:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0008_auto_20221026_0946'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ingredientrecipe',
            options={'verbose_name_plural': 'Ингредиент с рецептом'},
        ),
        migrations.AlterModelOptions(
            name='measureingridient',
            options={'verbose_name_plural': 'Единица измерения'},
        ),
        migrations.AlterModelOptions(
            name='shoppingcart',
            options={'verbose_name_plural': 'Корзина'},
        ),
        migrations.AlterModelOptions(
            name='tagrecipe',
            options={'verbose_name_plural': 'Тег с рецептом'},
        ),
        migrations.AddField(
            model_name='ingredientrecipe',
            name='amount',
            field=models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.DeleteModel(
            name='IngredientAmount',
        ),
    ]
