# Generated by Django 3.2 on 2022-10-27 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0010_auto_20221027_1255'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='measurement_unit',
            field=models.CharField(max_length=200),
        ),
        migrations.DeleteModel(
            name='MeasureIngridient',
        ),
    ]
